dist: trusty
sudo: required
language: minimal

services:
  - docker

before_script:
  - bash -x ${TRAVIS_BUILD_DIR}/tensorflow_io/kafka/python/kernel_tests/kafka_test.sh start kafka
  - bash -x ${TRAVIS_BUILD_DIR}/tensorflow_io/ignite/python/tests/start_ignite.sh

matrix:
  include:
  - name: "Python 2.7 Build"
    env: PYTHON_VERSION=2.7
  - name: "Python 3.4 Build"
    env: PYTHON_VERSION=3.4
  - name: "Python 3.5 Build"
    env: PYTHON_VERSION=3.5
  - name: "Python 3.6 Build"
    env: PYTHON_VERSION=3.6
script:
  - docker run -i -t --rm -v ${PWD}:/working_dir -w /working_dir tensorflow/tensorflow:custom-op bash -x /working_dir/.travis/python.release.sh ${PYTHON_VERSION}

notifications:
  email: false
