name: GitHub CI

on:
  push:
  pull_request:
    branches:
      - master

env:
  BAZEL_VERSION: 2.0.0
  BAZEL_OPTIMIZATION: --copt=-msse4.2 --copt=-mavx --compilation_mode=opt

jobs:
  macos-bazel:
    name: Bazel macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bazel on macOS
        run: |
          set -x -e
          echo $PATH
          /usr/bin/python3 --version
          python3 --version
          /usr/bin/python3 -m pip install tensorflow
          /usr/bin/python3 -c 'import site; print(site.getsitepackages())'
          /usr/bin/python3 -c 'import tensorflow as tf; print(tf.version.VERSION)'

