name: GitHub CI

on:
  push:
  pull_request:
    branches:
      - master

env:
  BAZEL_VERSION: 2.0.0
  BAZEL_OPTIMIZATION: --copt=-msse4.2 --copt=-mavx --compilation_mode=opt

jobs:
  windows-bazel:
    name: Bazel Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7.6
      - name: Bazel on Windows
        env:
          PYTHON_VERSION: 3.7.6
          BAZEL_VC: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/"
        shell: cmd
        run: |
          @echo on
          choco install cmake
          cmake --version
          curl -OL https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz
          tar -xzf hdf5-1.10.6.tar.gz
          ls -la
