name: GitHub CI

on:
  push:
  pull_request:
    branches:
      - master

env:
  BAZEL_VERSION: 2.0.0
  BAZEL_OPTIMIZATION: --copt=-msse4.2 --copt=-mavx --compilation_mode=opt

jobs:
  macos-bazel:
    name: Bazel macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bazel on macOS
        run: |
          set -x -e
          export PATH=/usr/bin:$PATH
          echo $PATH
          sudo sed -i.bak 's/sys.modules.values()/list(sys.modules.values())/g' /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py
          python3 --version
          sudo python3 -m pip install tensorflow
          python3 -c 'import site; print(site.getsitepackages())'
          python3 -c 'import tensorflow as tf; print(tf.version.VERSION)'

