name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git shortlog "v0.23.0..HEAD" -s
      - run: python3 tools/release/note_create.py
      - run: python3 tools/release/note_update.py
      - uses: peter-evans/create-pull-request@v3
